# Generated by Django 5.0.6 on 2024-07-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_loanrequestform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanRequestForm',
        ),
    ]
